### ISSUE TITLE
Related Julia software

### ISSUE THREAD

**Issue by dpsanders** [xoopR/set6#64]
The following related Julia software should perhaps be referenced in the paper:

- https://github.com/JuliaReach/LazySets.jl
- https://github.com/JuliaApproximation/DomainSets.jl

Part of JOSS review https://github.com/openjournals/joss-reviews/issues/2598

**Comment by RaphaelS1** [comment]
Thanks David. I'm unsure about adding these as I'd argue that (just from briefly scanning the docs) both implement more complex mathematical objects that will likely never be in set6. As there are several Julia packages for more complicated handling of sets it could be clearer to instead just add a line pointing to Julia and the orgs instead?

**Comment by dpsanders** [comment]
Sorry, for some reason I missed your comment.

Yes I agree they are more complex; I just felt that you implied in the paper that there were no Julia packages with lazy representations of sets. Maybe you can rewrite that paragraph. Thanks!

**Comment by RaphaelS1** [comment]
Ah I've re-read the part you're referring to and see what you mean. I've added the software you mentioned above. Please close this issue if you're happy with this.

**Comment by RaphaelS1** [comment]
@dpsanders just pinging you as you said you missed the last comment

**Comment by dpsanders** [comment]
@RaphaelS1 I don't see that reflected in the PDF?

**Comment by RaphaelS1** [comment]
Para 4:

" Similar packages in other computing languages include: i) portion (Decan, 2020) in Python, which only supports
intervals without generalisation to other mathematical sets; ii) IntervalSets.jl (Navelkar,
2016) in Julia, which is again limited to intervals though with good features for infix operators
and inspection; iii) a variety of packages in the JuliaIntervals suite (https://juliapackages.
com/u/juliaintervals), which primarily focus on rigorous arithmetic implementation; **and iv)
LazySets.jl (Forets & Schilling, 2018) and DomainSets.jl (Huybrechs, 2018) which both
faciliate symbolic representation of sets and infinite intervals in Julia.**"

**Comment by dpsanders** [comment]
Thanks, I think I was looking at the wrong version of PDF - apologies.
