### ISSUE TITLE
relative complement of two intervals

### ISSUE THREAD

**Issue by urswilke** [xoopR/set6#65]
Thank you for the interesting package!

I was wondering if the result of this code

``` r
library(set6)
i1 <- Interval$new(0, 2)
i2 <- Interval$new(0, 1, type = "[)")
i1 - i2
#> (1,2]
```
shouldn't be:

`[1,2]`.

**Comment by RaphaelS1** [comment]
Hey thanks for spotting this. It looks like the bug is slightly bigger than that, no matter what `type` is it's returning the same interval type, will fix this asap

**Comment by RaphaelS1** [comment]
Closed in 110fac43deff69adc77927881f9aa66a54c14fe9

**Comment by urswilke** [comment]
Thanks for the quick fix and glad if I could help. 

I remember already having wished for a clean way to deal with (sets of) intervals. Your approach looks really amazing.

**Comment by RaphaelS1** [comment]
Thanks :) !
