### ISSUE TITLE
Set$equals() behavior when one or both sets are empty

### ISSUE THREAD

**Issue by MrShoenel** [xoopR/set6#75]
I observed that when one **or** both sets in `$equals()` call are empty, the method always returns `TRUE` (the latter is fine). Is this intended behavior? See following code:

    s0 <- Set$new()
    s1 <- Set$new()
    s0$equals(s1)
    [1] TRUE # OK so far

    s1$add("foo")
    s0$equals(s1)
    [1] TRUE # is this true because no elements of s0 are compared to no elements of s1?
    s1$equals(s0)
    [1] TRUE # this can't be right, right?

**Comment by RaphaelS1** [comment]
Excellent spot thanks! Closed in https://github.com/xoopR/set6/pull/76

**Comment by MrShoenel** [comment]
Great, glad to help!
